"""Browser regression checks. Requires Python Playwright and local Chrome."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

url=os.environ.get('SITE_URL',Path(__file__).resolve().with_name('index.html').as_uri())
out=Path(__file__).resolve().parent/'tmp'
out.mkdir(exist_ok=True)
errors=[]
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe',headless=True)
    page=b.new_page(viewport={'width':1440,'height':1100})
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(url,wait_until='networkidle')
    expect(page.locator('#problem-answer')).to_be_hidden()
    page.locator('#reveal').click()
    expect(page.locator('#problem-answer')).to_be_visible()
    page.locator('#to-compare').click()
    for case,expected in [('A',['2']*3),('B',['2']*5),('C',['2','3','2','1','2','3','2','1','2'])]:
        page.locator(f'[data-case="{case}"]').click()
        page.locator('#all').click()
        assert page.locator('#voltage-row td').all_text_contents()==expected
    page.locator('[data-case="B"]').click()
    page.locator('#start').select_option('1')
    page.locator('#all').click()
    assert page.locator('#voltage-row td').all_text_contents()==['3','1','3','1']
    page.locator('[data-panel="lab"]').click()
    expect(page.locator('#alias-status')).to_contain_text('150 Hz')
    expect(page.locator('#lab-chart .alias')).to_have_count(1)
    def slider(name,value):
        page.locator('#'+name).fill(str(value))
    slider('frequency',600)
    slider('rate',1000)
    expect(page.locator('#frequency-output')).to_have_text('600 Hz')
    expect(page.locator('#alias-status')).to_contain_text('400 Hz')
    page.locator('#offset').select_option('0.5')
    # Compare rendered SVG sample coordinates to the smooth alias path by its model value.
    assert page.evaluate('''()=>{
      const m=Sampling.sample(1000,.5,20,600),a=Sampling.alias(m);
      return m.points.every(p=>Math.abs(p.u-a.value(p.t))<1e-8);
    }''')
    page.screenshot(path=str(out/'new-lab-desktop.png'),full_page=True)
    page.locator('#lab-original').uncheck()
    expect(page.locator('#lab-chart .signal')).to_have_count(0)
    expect(page.locator('#lab-chart .alias')).to_have_count(1)
    page.locator('#show-alias').uncheck()
    expect(page.locator('#lab-chart .alias')).to_have_count(0)
    page.locator('#show-alias').check()
    slider('rate',1500)
    expect(page.locator('#lab-status')).to_contain_text('Bedingung ist erfüllt')
    expect(page.locator('#lab-chart .alias')).to_have_count(0)
    slider('frequency',25)
    slider('rate',50)
    expect(page.locator('#lab-status')).to_contain_text('Genau auf der Grenze')
    expect(page.locator('#lab-chart .alias')).to_have_count(0)
    page.locator('#offset').select_option('0')
    expect(page.locator('#alias-status')).to_contain_text('konstante Spannung von 2 V')
    page.locator('#window').select_option('100')
    expect(page.locator('#lab-chart text').filter(has_text='100')).to_have_count(1)
    page.locator('#lab-reset').click()
    expect(page.locator('#frequency')).to_have_value('250')
    expect(page.locator('#rate')).to_have_value('400')
    expect(page.locator('#lab-original')).to_be_checked()
    expect(page.locator('#show-alias')).to_be_checked()
    page.locator('#frequency').focus()
    page.keyboard.press('ArrowRight')
    expect(page.locator('#frequency-output')).to_have_text('275 Hz')
    page.locator('[data-panel="wheel"]').click()
    expect(page.locator('#wheel-rotor svg')).to_have_count(1)
    expect(page.locator('#camera')).to_have_count(0)
    expect(page.locator('#wheel-play')).to_have_text('Pause')
    pose=page.locator('#wheel-blades').get_attribute('transform')
    page.wait_for_timeout(250)
    assert pose!=page.locator('#wheel-blades').get_attribute('transform')
    # Changing speed must never stop or reset the running animation.
    slider('rotation',9)
    expect(page.locator('#wheel-play')).to_have_attribute('aria-pressed','true')
    expect(page.locator('#wheel-apparent-output')).to_have_text('3 U/s')
    expect(page.locator('#wheel-direction')).to_contain_text('rückwärts')
    expect(page.locator('#wheel-signal .alias-wave').first).to_be_visible()
    # The signal cursor is the projection of the displayed rotor, for either view.
    def check_projection():
        assert page.evaluate('''()=>{
          const angle=Number(document.querySelector('#wheel-blades').getAttribute('transform').match(/rotate\\(([-.0-9]+)/)[1]);
          const cy=Number(document.querySelector('#wheel-signal .current-value').getAttribute('cy'));
          return Math.abs((224-cy)/57-(2+Math.sin(angle*Math.PI/180)))<1e-7;
        }''')
    check_projection()
    page.locator('#wheel-actual').check()
    expect(page.locator('#wheel-view-label')).to_have_text('Tatsächliche Bewegung')
    check_projection()
    page.locator('#wheel-actual').uncheck()
    slider('rotation',12)
    expect(page.locator('#wheel-apparent-output')).to_have_text('0 U/s')
    expect(page.locator('#wheel-direction')).to_contain_text('Stillstand')
    pose=page.locator('#wheel-blades').get_attribute('transform')
    page.wait_for_timeout(250)
    angle=lambda s:float(s.split('(')[1].split(' ')[0])
    assert abs(angle(pose)-angle(page.locator('#wheel-blades').get_attribute('transform')))<1e-6
    slider('rotation',13)
    expect(page.locator('#wheel-apparent-output')).to_have_text('1 U/s')
    expect(page.locator('#wheel-direction')).to_contain_text('vorwärts')
    slider('rotation',6)
    expect(page.locator('#wheel-direction')).to_contain_text('mehrdeutig')
    slider('rotation',0)
    expect(page.locator('#wheel-apparent-output')).to_have_text('0 U/s')
    slider('rotation',9)
    expect(page.locator('#wheel-apparent-output')).to_have_text('3 U/s')
    page.wait_for_timeout(500)
    page.locator('#wheel-play').click()
    expect(page.locator('#wheel-play')).to_have_text('Weiterlaufen')
    pose=page.locator('#wheel-blades').get_attribute('transform')
    page.wait_for_timeout(200)
    assert pose==page.locator('#wheel-blades').get_attribute('transform')
    slider('rotation',10)
    expect(page.locator('#wheel-play')).to_have_attribute('aria-pressed','false')
    check_projection()
    page.screenshot(path=str(out/'single-wheel-desktop.png'),full_page=True)
    page.locator('#wheel-play').click()
    page.locator('[data-panel="rule"]').click()
    pose=page.locator('#wheel-blades').get_attribute('transform')
    page.wait_for_timeout(200)
    assert pose==page.locator('#wheel-blades').get_attribute('transform')
    page.locator('#rule-reveal').click()
    expect(page.locator('#theorem')).to_be_visible()
    page.locator('input[name="choice"][value="1000"]').check()
    page.locator('#check-choice').click()
    expect(page.locator('#choice-feedback')).to_contain_text('Richtig')
    for width in [390,768]:
        page.set_viewport_size({'width':width,'height':850})
        for panel in ['problem','compare','lab','wheel','rule']:
            page.locator(f'[data-panel="{panel}"]').click()
            assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),(width,panel)
            if panel in ['lab','wheel']:page.screenshot(path=str(out/f'new-{panel}-{width}.png'),full_page=True)
    page.goto(url+'#wheel')
    expect(page.locator('#wheel')).to_be_visible()
    page.locator('[data-panel="lab"]').click()
    expect(page.locator('#lab')).to_be_visible()
    page.get_by_role('link',name='Impressum / Rechtliches',exact=True).click()
    expect(page.get_by_role('heading',name='Impressum / Rechtliches',exact=True)).to_be_visible()
    assert not errors,errors
    b.close()
print('Browser checks passed: worksheet, variable sine, alias, propeller, controls, keyboard, navigation and mobile layout.')
